# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import network_pb2 as network__pb2


class TheNetworkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAlignment = channel.unary_unary(
                '/thenetwork.TheNetwork/GetAlignment',
                request_serializer=network__pb2.FrameRequest.SerializeToString,
                response_deserializer=network__pb2.Alignment.FromString,
                )
        self.GetNetworkMovements = channel.unary_unary(
                '/thenetwork.TheNetwork/GetNetworkMovements',
                request_serializer=network__pb2.FrameRequest.SerializeToString,
                response_deserializer=network__pb2.NetworkMovements.FromString,
                )


class TheNetworkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAlignment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworkMovements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TheNetworkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAlignment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlignment,
                    request_deserializer=network__pb2.FrameRequest.FromString,
                    response_serializer=network__pb2.Alignment.SerializeToString,
            ),
            'GetNetworkMovements': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkMovements,
                    request_deserializer=network__pb2.FrameRequest.FromString,
                    response_serializer=network__pb2.NetworkMovements.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'thenetwork.TheNetwork', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TheNetwork(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAlignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/thenetwork.TheNetwork/GetAlignment',
            network__pb2.FrameRequest.SerializeToString,
            network__pb2.Alignment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNetworkMovements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/thenetwork.TheNetwork/GetNetworkMovements',
            network__pb2.FrameRequest.SerializeToString,
            network__pb2.NetworkMovements.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
